# Generated by Django 4.2 on 2024-04-04 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0010_alter_budget_month_alter_budget_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
